name: bump
on:
  workflow_call:
    inputs:
      bumpAmount:
        type: string
        required: false
        default: patch
        description: Semver segment to bump (→ v[major].[minor].[patch])
      releaseBranch:
        type: string
        required: false
        default: main
        description: The branch that will create release tags
      releaseTitle:
        type: string
        required: false
        default: |-
          {{#if oldTag}}{{repo.slug}} {{newTag}}{{else}}[Initial release] {{repo.slug}} {{newTag}}{{/if}}
        description: |-
          Handlebars template for release title

          Available variables: repo.owner, repo.name, repo.slug, repo.url, oldTag, newTag
      releaseBody:
        type: string
        required: false
        default: |-
          {{#if oldTag}}[{{oldTag}}]({{repo.url}}/tree/{{oldTag}}) [→]({{repo.url}}/compare/{{oldTag}}...{{newTag}}) [{{newTag}}]({{repo.url}}/tree/{{newTag}}){{else}}[{{newTag}}]({{repo.url}}/tree/{{newTag}}){{/if}}
        description: |-
          Handlebars template for release body

          Available variables: repo.owner, repo.name, repo.slug, repo.url, oldTag, newTag
      makeLatest:
        type: string
        required: false
        default: true
    outputs:
      oldTag:
        description: Name of the old tag used for relative bumping
        value: ${{ jobs.job.outputs.oldTag }}
      newTag:
        description: Name of the newly created git tag
        value: ${{ jobs.job.outputs.newTag }}
      newSemver:
        description: Semver notation of the newly created git tag
        value: ${{ jobs.job.outputs.newSemver }}
      releaseId:
        description: GitHub API ID of newly created release
        value: ${{ jobs.job.outputs.releaseId }}
      releaseUrl:
        description: HTML link to newly created release
        value: ${{ jobs.job.outputs.releaseUrl }}
      releaseTitle:
        description: Title of the newly created release with the Handlebars template rendered
        value: ${{ jobs.job.outputs.releaseTitle }}
      releaseBody:
        description: Description of the newly created release with the Handlebars template rendered
        value: ${{ jobs.job.outputs.releaseBody }}
jobs:
  job:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: createTag
        id: createTag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: ${{ inputs.bumpAmount }}
          RELEASE_BRANCHES: ${{ inputs.releaseBranch }}
      - name: extractSemvers
        id: extractSemvers
        uses: jaidlab/action-run-typescript@main
        with:
          globals: '{steps: ${{ toJson(steps) }}}'
          code: |-
            const extractSemver = (tag: string) => {
              return /(?<versionPrefix>v?)(?<version>\d+\.\d+\.\d+)/.exec(tag)?.groups
            }
            const oldTag = steps.createTag.outputs.old_tag
            const newTag = steps.createTag.outputs.new_tag
            const newSemver = extractSemver(newTag)
            core.setOutput('newSemver', newSemver?.version ?? '')
            const getSummary = () => {
              if (!oldTag) {
                return `[${newTag}](${github.event.repository.html_url}/releases/tag/${newTag})`
              }
              return `[${oldTag}](${github.event.repository.html_url}/releases/tag/${oldTag}) → [${newTag}](${github.event.repository.html_url}/releases/tag/${newTag})`
            }
            core.summary.addRaw(getSummary())
            core.summary.addEOL()
            core.summary.addCodeBlock(JSON.stringify({oldTag, newTag, newSemver}, null, 2))
            await core.summary.write()
      - name: getReleaseTexts
        id: getReleaseTexts
        uses: jaidlab/action-run-typescript@main
        with:
          globals: |-
            {
              inputs: ${{ toJson(inputs) }},
              steps: ${{ toJson(steps) }}
            }
          dependencies: zeug
          code: |-
            import {renderHandlebars} from 'zeug'

            type templateContext = {
              newTag: string
              oldTag?: string
              repo: {
                name: string
                owner: string
                slug: string
              }
            }

            const repo = {
              name: github.repo?.repo ?? '',
              owner: github.repo?.owner ?? '',
            }
            repo.slug = `${repo.owner}/${repo.name}`
            repo.url = `https://github.com/${repo.slug}`

            const templateContext: templateContext = {
              newTag: steps.createTag.outputs.new_tag || '',
              oldTag: steps.createTag.outputs.old_tag || undefined,
              repo,
            }

            core.setOutput('title', renderHandlebars(inputs.releaseTitle, templateContext))
            core.setOutput('body', renderHandlebars(inputs.releaseBody, templateContext))
      - name: updateRelease
        id: updateRelease
        uses: ncipollo/release-action@v1.21.0
        with:
          allowUpdates: true
          name: ${{ steps.getReleaseTexts.outputs.title }}
          body: ${{ steps.getReleaseTexts.outputs.body }}
          tag: ${{ steps.createTag.outputs.new_tag }}
          makeLatest: ${{ inputs.makeLatest }}
      - name: prepareDispatch
        id: prepareDispatch
        uses: jaidlab/action-run-typescript@main
        with:
          globals: '{steps: ${{ toJson(steps) }}}'
          code: |-
            const output = {
              newSemver: steps.extractSemvers.outputs.newSemver,
              newTag: steps.createTag.outputs.new_tag,
              oldTag: steps.createTag.outputs.old_tag,
              releaseBody: steps.getReleaseTexts.outputs.body,
              releaseId: steps.updateRelease.outputs.id,
              releaseTitle: steps.getReleaseTexts.outputs.title,
              releaseUrl: steps.updateRelease.outputs.html_url,
            }
            core.setOutput('value', JSON.stringify(output))
      - name: triggerDispatch
        id: triggerDispatch
        uses: peter-evans/repository-dispatch@v4.0.1
        with:
          event-type: bumped
          client-payload: ${{ steps.prepareDispatch.outputs.value }}
    outputs:
      oldTag: ${{ steps.createTag.outputs.old_tag }}
      newTag: ${{ steps.createTag.outputs.new_tag }}
      newSemver: ${{ steps.extractSemvers.outputs.newSemver }}
      releaseId: ${{ steps.updateRelease.outputs.id }}
      releaseUrl: ${{ steps.updateRelease.outputs.html_url }}
      releaseTitle: ${{ steps.getReleaseTexts.outputs.title }}
      releaseBody: ${{ steps.getReleaseTexts.outputs.body }}
